name: rell_trader
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  double_tap_to_exit: ^1.0.1
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  fl_chart: ^0.67.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  flutter_spinkit: ^5.2.1
  get: ^4.6.6
  http: ^1.2.1
  intl: ^0.19.0
  web_socket_channel: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
