// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_-5zCTS5-I7sloFA9JXHPy65fTO3PJak',
    appId: '1:1017466194314:web:6ecc53db4b81680a276073',
    messagingSenderId: '1017466194314',
    projectId: 'signal-3c033',
    authDomain: 'signal-3c033.firebaseapp.com',
    storageBucket: 'signal-3c033.appspot.com',
    measurementId: 'G-6ZRZ8SQWY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdI5psj6K1OccWTZD_qXWHF8NCgx2lELA',
    appId: '1:1017466194314:android:98969f1fa5703149276073',
    messagingSenderId: '1017466194314',
    projectId: 'signal-3c033',
    storageBucket: 'signal-3c033.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfPW8FBgNvMOkAp8577VsteTD79wDcoWY',
    appId: '1:1017466194314:ios:4c1fcd96a8597ea6276073',
    messagingSenderId: '1017466194314',
    projectId: 'signal-3c033',
    storageBucket: 'signal-3c033.appspot.com',
    iosBundleId: 'com.example.rellTrader',
  );
}
